version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  groups:
    app-dependencies:
      patterns:
        - "*"

- package-ecosystem: npm
  directory: "/typescript-sdk"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    typescript-sdk-dependencies:
      patterns:
        - "*"

- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    ui-dependencies:
      patterns:
        - "*"

- package-ecosystem: npm
  directory: "/ui/ui-app"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    ui-app-dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "eslint"
    eslint:
      patterns:
        - "eslint"
      update-types:
        - "patch"
        - "minor"

- package-ecosystem: npm
  directory: "/ui/ui-editors"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    ui-editors-dependencies:
      patterns:
        - "*"
      update-types:
        - "patch"
        - "minor"

- package-ecosystem: npm
  directory: "/ui/tests"
  schedule:
    interval: daily
  versioning-strategy: increase
  groups:
    ui-tests-dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "eslint"
    eslint:
      patterns:
        - "eslint"
      update-types:
        - "patch"
        - "minor"

- package-ecosystem: npm
  directory: "/docs-playbook"
  schedule:
    interval: weekly
  versioning-strategy: increase
  groups:
    docs-playbook-dependencies:
      patterns:
        - "*"
      update-types:
        - "patch"
