kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres
          env:
            - name: POSTGRES_ADMIN_PASSWORD
              value: admin # TODO: Change me!
            - name: POSTGRES_PASSWORD
              value: password # TODO: Change me!
            - name: POSTGRES_DB
              value: apicurio-studio
            - name: POSTGRES_USER
              value: apicurio-studio
            - name: PGDATA
              value: /postgresql/data
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
          volumeMounts:
            - name: postgresql
              mountPath: /postgresql
      volumes:
        - name: postgresql
          emptyDir: { }
