kind: Service
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
