apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-studio-app
  labels:
    app: apicurio-studio
    component: apicurio-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-studio-app
  template:
    metadata:
      labels:
        app: apicurio-studio
        component: apicurio-studio-app
    spec:
      containers:
        - name: apicurio-studio-app
          image: IMAGE_APP
          env:
            - name: QUARKUS_PROFILE
              value: prod
            - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
              value: 'true'
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: '*'

            - name: APICURIO_LOG_LEVEL
              value: DEBUG

            - name: APICURIO_STORAGE_DB_KIND
              value: postgresql
            - name: APICURIO_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/apicurio-studio
            - name: APICURIO_DATASOURCE_USERNAME
              value: apicurio-studio
            - name: APICURIO_DATASOURCE_PASSWORD
              value: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /apis/studio/v1/system/info
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /apis/studio/v1/system/info
              port: 8080
              scheme: HTTP
