apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-studio-ui
  labels:
    app: apicurio-studio
    component: apicurio-studio-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-studio-ui
  template:
    metadata:
      labels:
        app: apicurio-studio
        component: apicurio-studio-ui
    spec:
      containers:
        - name: apicurio-studio-ui
          image: IMAGE_UI
          env:
            - name: APICURIO_STUDIO_API_URL
              value: http://localhost:8080/apis/studio/v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
