# You might need to provide some additional configuration.
# Please read the comments below, and see other kustomize.yaml files.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../postgresql

  - deployment-app.yaml
  - service-app.yaml

  - deployment-ui.yaml
  - service-ui.yaml

images:
  - name: IMAGE_APP
    newName: quay.io/apicurio/apicurio-studio
    newTag: latest-snapshot
  - name: IMAGE_UI
    newName: quay.io/apicurio/apicurio-studio-ui
    newTag: latest-snapshot

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: apicurio-studio-ui
      spec:
        template:
          spec:
            containers:
              - name: apicurio-studio-ui
                env:
                  - name: APICURIO_STUDIO_API_URL
                    # TODO: Update this value with your clusters ingress router apps hostname. For example:
                    # value: http://apicurio-studio-app-apicurio-studio.apps.apicur.io/apis/studio/v1
                    value: http://apicurio-studio-app-NAMESPACE.INGRESS_ROUTER_APPS_HOSTNAME/apis/studio/v1
