apiVersion: v1
kind: Service
metadata:
  name: apicurio-studio-ui
  labels:
    app: apicurio-studio
spec:
  selector:
    component: apicurio-studio-ui
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
