apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: apicurio-studio-standalone
objects:
  # Apicurio API Deployment Configuration
  # #####################################
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-api
        template: apicurio-studio
      name: apicurio-studio-api
    spec:
      replicas: 1
      selector:
        app: apicurio-studio-api
        deploymentconfig: apicurio-studio-api
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: apicurio-studio-api
            deploymentconfig: apicurio-studio-api
            template: apicurio-studio
        spec:
          replicas: 1
          containers:
            - image: api:latest-release
              imagePullPolicy: Always
              name: apicurio-studio-api
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: APICURIO_KC_AUTH_URL
                  value: http://${AUTH_ROUTE}:8080
                - name: APICURIO_KC_REALM
                  value: ${KC_REALM}
                - name: APICURIO_KC_CLIENT_ID
                  value: ${API_APICURIO_KC_CLIENT_ID}
                - name: APICURIO_DB_DRIVER_NAME
                  value: postgresql
                - name: APICURIO_DB_CONNECTION_URL
                  value: jdbc:postgresql://studio-postgresql:5432/studio
                - name: APICURIO_HUB_STORAGE_JDBC_TYPE
                  value: postgresql9
                - name: APICURIO_DB_USER_NAME
                  value: apicurio
                - name: APICURIO_DB_PASSWORD
                  value: studio
                - name: APICURIO_MIN_HEAP
                  value: ${API_JVM_MIN}
                - name: APICURIO_MAX_HEAP
                  value: ${API_JVM_MAX}
                - name: QUARKUS_OIDC_TLS_VERIFICATION
                  value: "none"
              resources:
                limits:
                  cpu: ${API_CPU_LIMIT}
                  memory: ${API_MEM_LIMIT}
                requests:
                  cpu: ${API_CPU_REQUEST}
                  memory: ${API_MEM_REQUEST}
              livenessProbe:
                httpGet:
                  path: /system/ready
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /system/ready
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - apicurio-studio-api
            from:
              kind: ImageStreamTag
              name: 'api:latest-release'
        - type: ConfigChange
    status: {}
  # Apicurio WS Deployment Configuration
  # #####################################
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-ws
        template: apicurio-studio
      name: apicurio-studio-ws
    spec:
      replicas: 1
      selector:
        app: apicurio-studio-ws
        deploymentconfig: apicurio-studio-ws
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: apicurio-studio-ws
            deploymentconfig: apicurio-studio-ws
            template: apicurio-studio
        spec:
          replicas: 1
          containers:
            - image: ws:latest-release
              imagePullPolicy: Always
              name: apicurio-studio-ws
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: APICURIO_DB_DRIVER_NAME
                  value: postgresql
                - name: APICURIO_DB_CONNECTION_URL
                  value: jdbc:postgresql://studio-postgresql:5432/studio
                - name: APICURIO_HUB_STORAGE_JDBC_TYPE
                  value: postgresql9
                - name: APICURIO_DB_USER_NAME
                  value: apicurio
                - name: APICURIO_DB_PASSWORD
                  value: studio
                - name: APICURIO_MIN_HEAP
                  value: ${WS_JVM_MIN}
                - name: APICURIO_MAX_HEAP
                  value: ${WS_JVM_MAX}
                - name: QUARKUS_OIDC_TLS_VERIFICATION
                  value: "none"
              resources:
                limits:
                  cpu: ${WS_CPU_LIMIT}
                  memory: ${WS_MEM_LIMIT}
                requests:
                  cpu: ${WS_CPU_REQUEST}
                  memory: ${WS_MEM_REQUEST}
              livenessProbe:
                httpGet:
                  path: /metrics
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /metrics
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - apicurio-studio-ws
            from:
              kind: ImageStreamTag
              name: 'ws:latest-release'
        - type: ConfigChange
    status: {}
  # Apicurio UI Deployment Configuration
  # ####################################
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-ui
        template: apicurio-studio
      name: apicurio-studio-ui
    spec:
      replicas: 1
      selector:
        app: apicurio-studio-ui
        deploymentconfig: apicurio-studio-ui
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: apicurio-studio-ui
            deploymentconfig: apicurio-studio-ui
            template: apicurio-studio
        spec:
          replicas: 1
          containers:
            - image: ui:latest-release
              imagePullPolicy: Always
              name: apicurio-studio-ui
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: APICURIO_OIDC_REDIRECT_HTTPS
                  value: "false"
                - name: APICURIO_KC_AUTH_URL
                  value: http://${AUTH_ROUTE}:8080
                - name: APICURIO_KC_REALM
                  value: ${KC_REALM}
                - name: APICURIO_KC_CLIENT_ID
                  value: ${UI_APICURIO_KC_CLIENT_ID}
                - name: APICURIO_UI_HUB_API_URL
                  value: http://${API_ROUTE}:8080
                - name: APICURIO_UI_EDITING_URL
                  value: ws://${WS_ROUTE}:8080
                - name: APICURIO_UI_LOGOUT_REDIRECT_URI
                  value: /
                - name: APICURIO_MIN_HEAP
                  value: ${UI_JVM_MIN}
                - name: APICURIO_MAX_HEAP
                  value: ${UI_JVM_MAX}
                - name: QUARKUS_OIDC_TLS_VERIFICATION
                  value: "none"
                - name: QUARKUS_CORS_ALLOWED_ORIGINS
                  values: "*"
              resources:
                limits:
                  cpu: ${UI_CPU_LIMIT}
                  memory: ${UI_MEM_LIMIT}
                requests:
                  cpu: ${UI_CPU_REQUEST}
                  memory: ${UI_MEM_REQUEST}
              livenessProbe:
                httpGet:
                  path: /ready
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /ready
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 15
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - apicurio-studio-ui
            from:
              kind: ImageStreamTag
              name: 'ui:latest-release'
        - type: ConfigChange
    status: {}

# Template Parameters
parameters:
  - name: UI_ROUTE
    displayName: User Interface Route Name
    description: The route name to use for the UI.
    value: apicurio-studio-ui
    required: true
  - name: API_ROUTE
    displayName: API Route Name
    description: The route name to use for the API.
    value: apicurio-studio-api
    required: true
  - name: WS_ROUTE
    displayName: Editing Route Name
    description: The route name to use for editing layer (websocket based).
    value: apicurio-studio-ws
    required: true
  - name: AUTH_ROUTE
    displayName: Authentication Route Name
    description: The route name to use for Keycloak Authentication.
    value: apicurio-studio-auth
    required: true
  - name: KC_REALM
    displayName: Keycloak Realm
    description: The name of the Keycloak realm to use for authentication.
    value: apicurio
    required: true
  - name: API_APICURIO_KC_CLIENT_ID
    displayName: Keycloak Realm
    description: The name of the client-id for the API component.
    value: apicurio-api
    required: true
  - name: UI_APICURIO_KC_CLIENT_ID
    displayName: Keycloak Realm
    description: The name of the client-id for the UI component.
    value: apicurio-studio
    required: true
  - name: UI_JVM_MIN
    displayName: UI Min JVM Memory Limit
    description: UI Min JVM Memory Limit
    value: 512m
    required: false
  - name: UI_JVM_MAX
    displayName: UI Max JVM Memory Limit
    description: UI Max JVM Memory Limit
    value: 1200m
    required: false
  - name: UI_MEM_LIMIT
    displayName: UI Max Memory Limit
    description: UI Pods Max Memory Limit
    value: 1500Mi
    required: true
  - name: UI_MEM_REQUEST
    displayName: UI Memory Request
    description: UI Pods Memory Request
    value: 700Mi
    required: true
  - name: UI_CPU_LIMIT
    displayName: UI Max CPU Limit
    description: UI Pods Max CPU Limit
    value: '1'
    required: true
  - name: UI_CPU_REQUEST
    displayName: UI CPU Request
    description: UI Pods CPU Request
    value: 100m
    required: true
  - name: API_JVM_MIN
    displayName: API Min JVM Memory Limit
    description: API Min JVM Memory Limit
    value: 512m
    required: false
  - name: API_JVM_MAX
    displayName: API Max JVM Memory Limit
    description: API Max JVM Memory Limit
    value: 1400m
    required: false
  - name: API_MEM_LIMIT
    displayName: API Max Memory Limit
    description: API Pods Max Memory Limit
    value: 1700Mi
    required: true
  - name: API_MEM_REQUEST
    displayName: API Memory Request
    description: API Pods Memory Request
    value: 800Mi
    required: true
  - name: API_CPU_LIMIT
    displayName: API Max CPU Limit
    description: API Pods Max CPU Limit
    value: '1'
    required: true
  - name: API_CPU_REQUEST
    displayName: API CPU Request
    description: API Pods CPU Request
    value: 100m
    required: true
  - name: WS_JVM_MIN
    displayName: WS Min JVM Memory Limit
    description: WS Min JVM Memory Limit
    value: 512m
    required: false
  - name: WS_JVM_MAX
    displayName: WS Max JVM Memory Limit
    description: WS Max JVM Memory Limit
    value: 1400m
    required: false
  - name: WS_MEM_LIMIT
    displayName: WS Max Memory Limit
    description: WS Pods Max Memory Limit
    value: 1800Mi
    required: true
  - name: WS_MEM_REQUEST
    displayName: WS Memory Request
    description: WS Pods Memory Request
    value: 900Mi
    required: true
  - name: WS_CPU_LIMIT
    displayName: WS Max CPU Limit
    description: WS Pods Max CPU Limit
    value: '1'
    required: true
  - name: WS_CPU_REQUEST
    displayName: WS CPU Request
    description: WS Pods CPU Request
    value: 100m
    required: true
