apiVersion: v1
kind: Template
metadata:
  name: apicurio-studio-secrets-template
objects:
  # Persistent volumes: Keycloak and Postgresql
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: keycloak-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgresql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  # Secrets for: Keycloak and Postgresql
  - kind: Secret
    apiVersion: v1
    metadata:
      name: postgresql
      labels:
        app: postgresql
        template: apicurio-studio
    stringData:
      database-user: "${GENERATED_DB_USER}"
      database-password: "${GENERATED_DB_PASS}"
  - kind: Secret
    apiVersion: v1
    metadata:
      name: apicurio-studio-auth
      labels:
        app: apicurio-studio-auth
        template: apicurio-studio
    stringData:
      keycloak-user: "${GENERATED_KC_USER}"
      keycloak-password: "${GENERATED_KC_PASS}"
parameters:
  - name: GENERATED_KC_USER
    displayName: Keycloak Admin Username
    description: Username for the Keycloak admin user.
    generate: expression
    from: admin[A-Z0-9]{3}
    required: true
  - name: GENERATED_KC_PASS
    displayName: Keycloak Admin Password
    description: Password for the Keycloak admin user.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: GENERATED_DB_USER
    displayName: PostgreSQL Connection Username
    description: Username for PostgreSQL user that will be used for accessing the database.
    generate: expression
    from: user[A-Z0-9]{3}
    required: true
  - name: GENERATED_DB_PASS
    displayName: PostgreSQL Connection Password
    description: Password for the PostgreSQL connection user.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true