apiVersion: v1
kind: Template
metadata:
  name: apicurio-studio-standalone-template
objects:
  # The Routes: auth, api, ws, ui (no route needed for postgresql)
  - apiVersion: v1
    kind: Route
    metadata:
      name: apicurio-studio-auth
      creationTimestamp: null
      labels:
        app: apicurio-studio-auth
        template: apicurio-studio
    spec:
      to:
        kind: Service
        name: apicurio-studio-auth
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: apicurio-studio-api
      creationTimestamp: null
      labels:
        app: apicurio-studio-api
        template: apicurio-studio
    spec:
      to:
        kind: Service
        name: apicurio-studio-api
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: apicurio-studio-ws
      creationTimestamp: null
      labels:
        app: apicurio-studio-ws
        template: apicurio-studio
    spec:
      to:
        kind: Service
        name: apicurio-studio-ws
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: apicurio-studio-ui
      creationTimestamp: null
      labels:
        app: apicurio-studio-ui
        template: apicurio-studio
    spec:
      to:
        kind: Service
        name: apicurio-studio-ui
        weight: 100
      wildcardPolicy: None