apiVersion: v1
kind: Template
metadata:
  name: apicurio-studio-services-template
objects:
  # Services for: Keycloak, API, WS, UI
  - apiVersion: v1
    kind: Service
    metadata:
      name: studio-postgresql
      creationTimestamp: null
      labels:
        app: studio-postgresql
        template: apicurio-studio
    spec:
      ports:
        - name: studio-postgresql
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        app: studio-postgresql
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-auth
        template: apicurio-studio
      name: apicurio-studio-auth
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: apicurio-studio-auth
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: apicurio-studio-api
      labels:
        app: apicurio-studio-api
        template: apicurio-studio
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/system/metrics'
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: apicurio-studio-api
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: apicurio-studio-ws
      labels:
        app: apicurio-studio-ws
        template: apicurio-studio
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: apicurio-studio-ws
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-ui
        template: apicurio-studio
      name: apicurio-studio-ui
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: apicurio-studio-ui
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}