apiVersion: v1
kind: Template
metadata:
  name: apicurio-studio-image-streams-template
objects:
  # Image Streams for the Apicurio components
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: auth
    spec:
      tags:
        - name: latest-release
          from:
            kind: DockerImage
            name: apicurio/apicurio-studio-auth-quarkus:latest
          importPolicy:
            scheduled: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: api
    spec:
      tags:
        - name: latest-release
          from:
            kind: DockerImage
            name: apicurio/apicurio-studio-api-quarkus:latest
          importPolicy:
            scheduled: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ws
    spec:
      tags:
        - name: latest-release
          from:
            kind: DockerImage
            name: apicurio/apicurio-studio-ws-quarkus:latest
          importPolicy:
            scheduled: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ui
    spec:
      tags:
        - name: latest-release
          from:
            kind: DockerImage
            name: apicurio/apicurio-studio-ui-quarkus:latest
          importPolicy:
            scheduled: true