version: '3'

services:
  apicurio-studio-db:
    image: 'postgres:15.2'
    environment:
      POSTGRES_DB: ${AS_DATABASE}
      POSTGRES_USER: ${AS_DB_USER}
      POSTGRES_PASSWORD: ${AS_DB_PASSWORD}
    volumes:
      - 'postgre_apicurio:/var/lib/postgresql/data'
