version: '3'

volumes:
  mysql_apicurio:

services:
  apicurio-studio-db:
    image: 'percona:5.7'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: ${AS_DATABASE}
      MYSQL_ROOT_PASSWORD: ${AS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${AS_DB_USER}
      MYSQL_PASSWORD: ${AS_DB_PASSWORD}
    volumes:
      - 'mysql_apicurio:/var/lib/mysql'
