# This example template deploys Apicurio Studio with an ephemeral PostgreSQL storage.
#
# Steps:
#
# 1. Create or select a namespace:
#
# oc new-project apicurio-studio
#
# 2. Apply the template:
#
#  oc process -f template-simple-sql.yaml \
#  -p NAMESPACE=apicurio-studio \
#  -p INGRESS_ROUTER_APPS_HOSTNAME=apps.apicur.io \
#  | oc apply -f -
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: apicurio-studio-simple-sql
labels:
  template: apicurio-studio-simple-sql
objects:

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgresql
      namespace: ${NAMESPACE}
      labels:
        app: postgresql
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          labels:
            app: postgresql
        spec:
          containers:
            - name: postgresql
              image: postgres
              env:
                - name: POSTGRES_ADMIN_PASSWORD
                  value: admin # TODO: Change me!
                - name: POSTGRES_PASSWORD
                  value: password # TODO: Change me!
                - name: POSTGRES_DB
                  value: apicurio-studio
                - name: POSTGRES_USER
                  value: apicurio-studio
                - name: PGDATA
                  value: /postgresql/data
              ports:
                - name: postgresql
                  containerPort: 5432
                  protocol: TCP
              readinessProbe:
                tcpSocket:
                  port: 5432
              livenessProbe:
                tcpSocket:
                  port: 5432
              volumeMounts:
                - name: postgresql
                  mountPath: /postgresql
          volumes:
            - name: postgresql
              emptyDir: { }

  - apiVersion: v1
    kind: Service
    metadata:
      name: postgresql
      namespace: ${NAMESPACE}
      labels:
        app: postgresql
    spec:
      selector:
        app: postgresql
      ports:
        - name: postgresql
          port: 5432
          protocol: TCP
          targetPort: 5432

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: apicurio-studio-app
      namespace: ${NAMESPACE}
      labels:
        app: apicurio-studio
        component: apicurio-studio-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: apicurio-studio-app
      template:
        metadata:
          labels:
            app: apicurio-studio
            component: apicurio-studio-app
        spec:
          containers:
            - name: apicurio-studio-app
              image: quay.io/apicurio/apicurio-studio:latest-snapshot
              env:
                - name: QUARKUS_PROFILE
                  value: prod
                - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
                  value: 'true'
                - name: QUARKUS_HTTP_CORS_ORIGINS
                  value: '*'

                - name: APICURIO_LOG_LEVEL
                  value: DEBUG

                - name: APICURIO_STORAGE_DB_KIND
                  value: postgresql
                - name: APICURIO_DATASOURCE_URL
                  value: jdbc:postgresql://postgresql:5432/apicurio-studio
                - name: APICURIO_DATASOURCE_USERNAME
                  value: apicurio-studio
                - name: APICURIO_DATASOURCE_PASSWORD
                  value: password
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 200m
                  memory: 500Mi
                limits:
                  cpu: 500m
                  memory: 1000Mi
              livenessProbe:
                httpGet:
                  path: /apis/studio/v1/system/info
                  port: 8080
                  scheme: HTTP
              readinessProbe:
                httpGet:
                  path: /apis/studio/v1/system/info
                  port: 8080
                  scheme: HTTP

  - apiVersion: v1
    kind: Service
    metadata:
      name: apicurio-studio-app
      namespace: ${NAMESPACE}
      labels:
        app: apicurio-studio
    spec:
      selector:
        component: apicurio-studio-app
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: apicurio-studio-app
      namespace: ${NAMESPACE}
      labels:
        app: apicurio-studio
    spec:
      to:
        kind: Service
        name: apicurio-studio-app
        weight: 100
      wildcardPolicy: None

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: apicurio-studio-ui
      namespace: ${NAMESPACE}
      labels:
        app: apicurio-studio
        component: apicurio-studio-ui
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: apicurio-studio-ui
      template:
        metadata:
          labels:
            app: apicurio-studio
            component: apicurio-studio-ui
        spec:
          containers:
            - name: apicurio-studio-ui
              image: quay.io/apicurio/apicurio-studio-ui:latest-snapshot
              env:
                - name: APICURIO_STUDIO_API_URL
                  value: http://apicurio-studio-app-${NAMESPACE}.${INGRESS_ROUTER_APPS_HOSTNAME}/apis/studio/v1
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 250Mi
                limits:
                  cpu: 200m
                  memory: 500Mi
              livenessProbe:
                httpGet:
                  path: /config.js
                  port: 8080
                  scheme: HTTP
              readinessProbe:
                httpGet:
                  path: /config.js
                  port: 8080
                  scheme: HTTP

  - apiVersion: v1
    kind: Service
    metadata:
      name: apicurio-studio-ui
      namespace: ${NAMESPACE}
      labels:
        app: apicurio-studio
    spec:
      selector:
        component: apicurio-studio-ui
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: apicurio-studio
      name: apicurio-studio-ui
      namespace: ${NAMESPACE}
    spec:
      to:
        kind: Service
        name: apicurio-studio-ui
        weight: 100
      wildcardPolicy: None

parameters:
  - name: NAMESPACE
    required: true
  - name: INGRESS_ROUTER_APPS_HOSTNAME
    # Update this value with your clusters ingress router apps hostname. For example:
    # apps.apicur.io
    required: true
