include::partial$shared/all-attributes.adoc[]

[id="assembly-getting-started"]
= Getting started with {studio-long}

[role="_abstract"]
As an API owner or developer, you can use {studio-long} to design event schemas and API definitions that comply with vendor-neutral and portable open specifications.

In this quick start, you'll learn how to create an API definition or event schema from a simple or detailed template, import an existing design to edit it, test a design against rules configured in {registry-long}, and export a finished design to {registry-long}.

.Prerequisites
* If you plan to store your designs in {registry-long}, you have a running {registry} instance (see {registry-introduction}).

include::partial$proc-creating-api-design.adoc[leveloffset=+1]
include::partial$proc-creating-schema-design.adoc[leveloffset=+1]
include::partial$proc-importing-schema-api-design.adoc[leveloffset=+1]
include::partial$proc-testing-schema-api-design.adoc[leveloffset=+1]
include::partial$proc-exporting-schema-api-design.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
ifdef::apicurio-studio-downstream[]
* https://access.redhat.com/documentation/en-us/red_hat_build_of_apicurio_registry/2.5[{registry-long} user documentation]
endif::[]
ifndef::apicurio-studio-downstream[]
* https://www.apicur.io/registry/docs/apicurio-registry/2.5.x/index.html[{registry-long} user documentation]
endif::[]
