# You might need to provide some additional configuration.
# Please read the comments below, and see other kustomize.yaml files.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress-app.yaml
  - ingress-ui.yaml

patches:
  - patch: |
      - op: replace
        path: '/spec/rules/0/host'
        # TODO: Update this value with your clusters ingress router apps hostname. For example:
        # value: apicurio-studio-app-apicurio-studio.apps.apicur.io
        value: apicurio-studio-app-NAMESPACE.INGRESS_ROUTER_APPS_HOSTNAME
    target:
      kind: Ingress
      name: apicurio-studio-app
  - patch: |
      - op: replace
        path: '/spec/rules/0/host'
        # TODO: Update this value with your clusters ingress router apps hostname. For example:
        # value: apicurio-studio-app-apicurio-studio.apps.apicur.io
        value: apicurio-studio-ui-NAMESPACE.INGRESS_ROUTER_APPS_HOSTNAME
    target:
      kind: Ingress
      name: apicurio-studio-ui
