[id="studio-overview"]
= What is {studio-long}?

{studio-long} enables you to design schemas and API definitions. It provides a web console to make it easy for API owners and developers to manage the content of event schemas and API definitions.

You can use {studio} to create a schema or API design from a simple template, use one of the detailed templates provided, or import an existing design to edit it. When you’re happy with your content, you can save your design to a file, and export it to {registry-long} or use it in your client applications.

ifdef::apicurio-studio-downstream[]
{studio-long} is based on the https://github.com/Apicurio/apicurio-studio[Apicurio Studio] open source community project.
endif::[]

[id="studio-key-concepts"]
== Key concepts

To understand how {studio-long} works, it’s important to understand the following key concepts:

* *{studio-long} web console*
+
The web environment where users from an organization can manage designs.

* *Design*
+
An API design or schema design. When downloaded to a local project, or exported into {registry-long}, designs are referred to as _artifacts_.

[id="studio-capabilities"]
== {studio-long} capabilities

The {studio-long} has the following key capabilities:

* Creation of APIs and schemas in a visual editor
* Increased developer productivity with code and test generation from downloaded designs

[id="studio-use-cases"]
== {studio-long} use cases

The main use cases for {studio} are as follows:

* *Contract-first application development*
+
You can use {studio-long} to visually design the API and data models (_contracts_) required by your applications, before you write any application code. After you define the contract, it’s much easier to create the application logic needed to satisfy the contract. You can generate Quarkus-based client and server applications from designs created in {studio-long}.

* *Schema editing for Kafka applications*
+
When you use Kafka to produce and consume messages, you can define the data shape of your message payloads by using one of a number of event schema types. When you need to define a new schema, you can use {studio-long}.
