[id='proc-testing-schema-api-design_{context}']
= Testing a schema or API design
:imagesdir: ../_images

[role="_abstract"]
You can test that your schema or API design content is valid and compatible with existing content by applying the rules of an existing {product-long-registry} instance.
You can test the design while working in the {product-long-api-designer} editor, without exporting the design to {product-long-registry}.

.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
* You've created or imported a design in {product-api-designer}.
* You can access a running {product-registry} instance in your organization.
Within that instance, you know the artifact ID of an artifact with the required rules configured.
For more information, see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^].

.Procedure
. On the *API and Schema Designs* page of the {service-url-api-designer}[{product-long-api-designer} web console^], select the design that you want to test.
. Click the options icon (three vertical dots), and click *Edit design content* to open the design editor.
. From the *Actions* menu, click *Run {registry} check*.
. From the *Registry instance* list, select a {registry} instance.
. In the *Group* and *ID* fields, specify the artifact details.
. Click *Test*.

A new pane in the design editor window shows the registration issues found by the test:

* If the design content obeys the specified rules, the registration issues pane contains the following text:
`Registry Test completed with no issues`

* If the registration issues pane provides details of any issues, resolve the issues and click *Retry* to retest the content using the same artifact rules.


