[id="proc-creating-schema-draft"]
= Creating a schema draft

[role="_abstract"]
Use the {studio-long} web console to create an Apache Avro, JSON Schema, or Google Protocol Buffers (Protobuf) event schema.

.Prerequisites
* You're logged in to the {studio} web console.

.Procedure
. In the {studio} web console, click *Create draft*.
. Complete the wizard to provide the following details for the new draft:

.. Specify the *Draft Coordinates* and click *Next*:
+
*  *Group ID & Draft ID*: Use the default empty settings to automatically generate an Draft ID and add the Draft to the `default` Draft group. Alternatively, you can enter an optional Group ID or Draft ID.
* *Version number*: Optionally specify a version number.
* *Type*: Use the default *Auto-Detect* setting to automatically detect the Draft type (not allowed if creating an empty Draft), or select the Draft type from the list, for example, *Apache Avro*. 


.. Specify the *Draft Content* and click *Next*:
+
** *From template*: Choose from the list of templates.
* *From local file*: Click *Browse*, and select a file, or drag and drop a file. For example, `my-openapi.json` or `my-schema.proto`. Alternatively, you can enter the file contents in the text box.
* *From URL*: Enter a valid and accessible URL, and click *Fetch*. For example: `\https://petstore3.swagger.io/api/v3/openapi.json`.


.. Specify the *Draft Metadata*:
+
** *Name*: Enter an optional friendly name for the first artifact version.
** *Description*: Enter an optional description for the first artifact version.

. Click *Create* to create the draft.
The Draft details view is displayed.

. To edit the draft, click *Edit draft*.
+
.. Click the *Design* tab, and edit the draft.
.. _(Optional)_ To see the changes that you made since the last save, click *Actions > Show draft changes*.
.. _(Optional)_ In the left pane of the draft editor, you can add the following items:
.. Click *Save*.
.. Use the breadcrumbs to navigate back to the *Drafts* page.

The new draft is listed on the *Drafts* page using the Group ID and Draft ID.
You can use the options icon (three vertical dots) to view the draft details, edit the draft content, finalize the draft, view the draft in {registry}, or delete the draft.


.Additional information

See xref:proc-finalizing-draft[]
