[id="installing-studio-sql-storage-docker"]
= Installing {studio} with SQL database storage

[role="_abstract"]
This section explains how to install and run {studio} with storage in a PostgreSQL database from a container image. This storage option is suitable for production environments.

.Prerequisites

* You must have Docker installed and the Docker daemon running.
* Ensure that you can connect to the quay.io container repository.
* You must already have a PostgreSQL database server installed and running. For example: 
+
[source,bash]
----
$ postgres -D /usr/local/pgsql/data
----
+
For more details, see https://www.postgresql.org/docs/12/server-start.html
+
or
+
[source,bash]
----
$ docker run -it -p 5432:5432 -e POSTGRES_USER=apicurio-studio -e POSTGRES_PASSWORD=password postgres
----

.Procedure

. Get the {studio} application and web console container images:
+
[source,bash]
----
$ docker pull quay.io/apicurio/apicurio-studio:VERSION
$ docker pull quay.io/apicurio/apicurio-studio-ui:VERSION
----
+
`VERSION` is the {studio} release version, for example, `{studio-docker-version}`.

. Run the application container image:
+
[source,bash,subs=attributes+]
----
$ docker run -it -p 8080:8080 \
  -e APICURIO_STORAGE_DB_KIND=postgresql \
  -e APICURIO_DATASOURCE_URL=jdbc:postgresql://localhost:5432/apicurio-studio \
  -e APICURIO_DATASOURCE_USERNAME=apicurio-studio \
  -e APICURIO_DATASOURCE_PASSWORD=password \
  --network host \
  quay.io/apicurio/apicurio-studio:{studio-docker-version}
----

. Run the web console container image:
+
[source,bash,subs=attributes+]
----
$ docker run -it -p 8888:8080 quay.io/apicurio/apicurio-studio-ui:{studio-docker-version}
----
+
The {studio} web console will be available at http://localhost:8888[].

. Send a test request using the {studio} REST API. For example, enter the following `curl` command to get a list of API designs:
+
[source,bash]
----
$ curl http://localhost:8080/apis/studio/v1/designs
----

. Verify that the response is similar to the following example:
+
[source,bash]
----
{"kind":"DesignSearchResults","count":0,"page":1,"pageSize":20,"designs":[]}
----

[role="_additional-resources"]
.Additional resources
* For more REST API sample requests, see the {studio-rest-api}.
* For demonstration examples, see {studio-examples}.
* For more details on PostgreSQL, see the link:https://www.postgresql.org/docs/12/index.html[PostgreSQL documentation].
