[id="installing-studio-in-memory-storage-docker"]
= Installing {studio} with in-memory storage

[role="_abstract"]
This section explains how to install and run {studio} with simple in-memory storage from a container image.

NOTE: The in-memory storage option is suitable for development only. All data is lost when the container image is restarted.  

.Prerequisites

* You must have Docker installed and the Docker daemon running.
* Ensure that you can connect to the quay.io container repository.

.Procedure

. Get the {studio} application and web console container images:
+
[source,bash]
----
$ docker pull quay.io/apicurio/apicurio-studio:VERSION
$ docker pull quay.io/apicurio/apicurio-studio-ui:VERSION
----
+ 
`VERSION` is the {studio} release version, for example, `{studio-docker-version}`.

. Run the application container image:
+
[source,bash,subs=attributes+]
----
$ docker run -it -p 8080:8080 quay.io/apicurio/apicurio-studio:{studio-docker-version}
----

. Run the web console container image:
+
[source,bash,subs=attributes+]
----
$ docker run -it -p 8888:8080 quay.io/apicurio/apicurio-studio-ui:{studio-docker-version}
----
+
The {studio} web console will be available at http://localhost:8888[].

. Send a test request using the {studio} REST API. For example, enter the following `curl` command to get a list of API designs:
+
[source,bash]
----
$ curl http://localhost:8080/apis/studio/v1/designs
----

. Verify that the response is similar to the following example:
+
[source,bash]
----
{"kind":"DesignSearchResults","count":0,"page":1,"pageSize":20,"designs":[]}
----

[role="_additional-resources"]
.Additional resources
* For more REST API sample requests, see the {studio-rest-api}.
* For demonstration examples, see {studio-examples}.
