services:
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.9
    container_name: apicurio-studio-inmemorynoauth_registry-api
    environment:
      apicurio.rest.deletion.group.enabled: "true"
      apicurio.rest.deletion.artifact.enabled: "true"
      apicurio.rest.deletion.artifact-version.enabled: "true"
      apicurio.rest.mutability.artifact-version-content.enabled: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
    ports:
      - "8080:8080"

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.9
    container_name: apicurio-studio-inmemorynoauth_registry-ui
    ports:
      - "8081:8080"
    depends_on:
      - apicurio-registry

  apicurio-studio-ui:
    image: apicurio/apicurio-studio-ui:1.1.0-Beta4
    container_name: apicurio-studio-inmemorynoauth_studio-ui
    ports:
      - "8888:8080"
    depends_on:
      - apicurio-registry
