services:
  # Define the Apicurio Registry service
  apicurio-registry:
    image: apicurio/apicurio-registry:latest-snapshot
    container_name: apicurio-studio-getting-started-context-path_registry
    environment:
      - apicurio.rest.deletion.group.enabled=true
      - apicurio.rest.deletion.artifact.enabled=true
      - apicurio.rest.deletion.artifact-version.enabled=true
      - apicurio.rest.mutability.artifact-version-content.enabled=true
      - QUARKUS_HTTP_CORS_ORIGINS=*
    ports:
      - "8080:8080"

  # Define the Apicurio Studio service
  apicurio-studio:
    image: apicurio/apicurio-studio-ui:latest-snapshot
    container_name: apicurio-studio-getting-started-context-path_studio
    environment:
      - APICURIO_CONTEXT_PATH=/studio/
    depends_on:
      - apicurio-registry

  # Define the Nginx reverse proxy service
  nginx:
    image: nginx
    container_name: apicurio-studio-getting-started-context-path_proxy
    ports:
      - "8888:8080" # Expose the reverse proxy on port 8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx config
    depends_on:
      - apicurio-studio
