site:
  title: Apicurio Studio PREVIEW
  url: https://www.apicur.io/registry/docs
  start_page: apicurio-studio::index.adoc
content:
  edit_url: https://github.com/Apicurio/apicurio-studio/tree/main/docs
  sources:
    - url: ../
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://raw.githubusercontent.com/Apicurio/apicurio-docs-ui/main/dist/ui-bundle.zip
    snapshot: true

runtime:
  cache_dir: ./target/antora-cache

output:
  dir: ./target/dist

asciidoc:
  attributes:
    plantuml-server-url: https://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    mod-loc: partial$
    attachments-dir: _attachments
