version: '2'

services:

  postgresql:
    container_name: apicurio-studio-postgresql
    image: postgres
    environment:
      POSTGRES_USER: apicurio-studio
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  app:
    image: quay.io/apicurio/apicurio-studio:latest-snapshot
    environment:
      APICURIO_LOG_LEVEL: DEBUG
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_ACCESS-LOG_ENABLED: 'true'
      QUARKUS_HTTP_CORS_ORIGINS: '*'
      APICURIO_STORAGE_DB_KIND: postgresql
      APICURIO_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/apicurio-studio
      APICURIO_DATASOURCE_USERNAME: apicurio-studio
      APICURIO_DATASOURCE_PASSWORD: password
    ports:
      - '8080:8080'
    depends_on:
      - postgresql

  ui:
    image: quay.io/apicurio/apicurio-studio-ui:latest-snapshot
    environment:
      APICURIO_STUDIO_API_URL: http://localhost:8080/apis/studio/v1
    ports:
      - '8888:8080'
    depends_on:
      - app
