version: '2'

services:

  app:
    image: quay.io/apicurio/apicurio-studio:latest-snapshot
    ports:
      - '8080:8080'

  ui:
    image: quay.io/apicurio/apicurio-studio-ui:latest-snapshot
    ports:
      - '8888:8080'
    depends_on:
      - app
