name: Build & Verify Typescript SDK

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
      - 'CONTRIBUTING.md'
      - 'dco.txt'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
      - 'CONTRIBUTING.md'
      - 'dco.txt'
    branches: [main]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-test:
    name: Build Typescript SDK
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v3

      # Set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'typescript-sdk/**/package-lock.json'

      - name: Build Apicurio Studio typescript SDK
        run: |
          cd typescript-sdk
          npm install
          npm run generate-studio-sdk
          npm run lint
          npm run build

      - name: Google Chat Notification (Always)
        if: github.event_name == 'push' && always()
        uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
        with:
          name: ${{ github.job }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}

      - name: Google Chat Notification (Error)
        if: github.event_name == 'push' && failure()
        uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
        with:
          name: ${{ github.job }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_ERRORS }}
          status: ${{ job.status }}
